# Generated by Django 4.2.23 on 2025-07-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('FURNITURE', 'Furniture'), ('INFRASTRUCTURE', 'Infrastructure'), ('MANAGEMENT_RENT', 'Management Rent'), ('EMPLOYEE_SALARY', 'Employee Salary'), ('Electricity', 'Electricity'), ('others', 'others')], max_length=20),
        ),
    ]
